install.packages("ggplot2")
install.packages("dplyr")
install.packages("data.table")
install.packages("xergm", repos='https://cran.uni-muenster.de', dependencies=TRUE)
install.packages("igraph")
install.packages("scales")
install.packages("lda")
require(devtools)
install_version("ISOcodes", version = "2018.06.29", repos = "https://cran.uni-muenster.de")
install_version("statnet.common", version = "4.1.2", repos = "https://cran.uni-muenster.de")
install_version("quanteda", version = "1.3.4", repos = "https://cran.uni-muenster.de")
install_version("dplyr", version = "0.8.0", repos='https://cran.uni-muenster.de', dependencies=TRUE)
