install.packages("ggplot2")
install.packages("dplyr")
install.packages("data.table")
install.packages("igraph")
install.packages("scales")
install.packages("lda")
require(devtools)
install_version("statnet.common", version = "4.1.2")
install_version("btergm", version = "1.9.3")
install_version("dplyr", version = "0.8.0", repos='https://cran.uni-muenster.de', dependencies=TRUE)
install_version("xergm", version = "1.8.2")
