install.packages("btergm", repos='http://cran.us.r-project.org', dependencies=TRUE)
install.packages("statnet", repos='http://cran.us.r-project.org', dependencies=TRUE)
install.packages("texreg", repos='http://cran.us.r-project.org', dependencies=TRUE)
install.packages("data.table", repos='http://cran.us.r-project.org', dependencies=TRUE)
install.packages("RSIENA", repos='http://cran.us.r-project.org', dependencies=TRUE)
install.packages("Matrix", repos='http://cran.us.r-project.org', dependencies=TRUE)
install.packages("metafor")
install.packages("DT")
install.packages("formattable")
install.packages("plyr")
install.packages("jtools")
install.packages("dotwhisker")
